force-app/main/default/objects/Voltas_Electrics__c/Voltas_Electrics__c.object-meta.xml
<CustomObject>
    <label>Voltas Electronics</label>
    <nameField>
        <label>Voltas Electrics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voltas Electronics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voltas_Electrics__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <label>Active Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Ocenia</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voltas_Electrics__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desktop &amp; Tablts</fullName>
            </value>
            <value>
                <fullName>Freezing Equipments</fullName>
            </value>
            <value>
                <fullName>Home Appliances</fullName>
            </value>
            <value>
                <fullName>Led &amp; Screen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestClass_eg1_VoltasClass.cls
@isTest
private class TestClass_eg1_VoltasClass {
    @isTest
    private static void method() {
        Voltas_Electrics__c vdC = new Voltas_Electrics__c();
        vdC.Name = 'Demo';
        vdC.Product_Type__c = 'Led & Screen';
        try {
            insert vdC;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        Voltas_Electrics__c VoltasData = [SELECT Id, Name, Product_Type__c, Active_Region__c FROM Voltas_Electrics__c ];
        System.assertEquals('Asia', VoltasData.Active_Region__c, 'Region should be Asia of Product Type is Led & Screen');
    }
}