force-app/main/default/objects/Voltas_Electrics__c/Voltas_Electrics__c.object-meta.xml
<CustomObject>
    <label>Voltas Electronics</label>
    <nameField>
        <label>Voltas Electrics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voltas Electronics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voltas_Electrics__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <label>Active Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Ocenia</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voltas_Electrics__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desktop &amp; Tablts</fullName>
            </value>
            <value>
                <fullName>Freezing Equipments</fullName>
            </value>
            <value>
                <fullName>Home Appliances</fullName>
            </value>
            <value>
                <fullName>Led &amp; Screen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Handler5Jan_eg1_onVoltas.cls
public class Handler5Jan_eg1_onVoltas {
	public static void method(List<Voltas_Electrics__c> voltasDataList)
    {
		if(!voltasDataList.isEmpty())
        {
			for(Voltas_Electrics__c vdL : voltasDataList)
                {
                    if(vdL.Product_Type__c == 'Led & Screen')
                    {
                        vdL.Active_Region__c = 'Asia';
                    }
                }
        }
    }
}